

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the job
jobs:
  build:
    # Run on an Ubuntu environment
    runs-on: ubuntu-latest

    # Steps to execute
    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17 (compatible with recent Spring Boot versions)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Cache Maven dependencies to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Compile and build the project
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Optional: Run tests if you have test cases (uncomment to enable)
      # - name: Run tests
      #   run: mvn test

      # Optional: Upload build artifacts (e.g., JAR file)
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-backend-artifact
          path: target/*.jar
